from ejemplo.models import Familiar, Pacientes, Operarios
Familiar(nombre="Rosario", direccion="Rio Parana 745", numero_pasaporte=123123).save()
Familiar(nombre="Alberto", direccion="Rio Parana 745", numero_pasaporte=890890).save()
Familiar(nombre="Samuel", direccion="Rio Parana 745", numero_pasaporte=345345).save()
Familiar(nombre="Florencia", direccion="Rio Parana 745", numero_pasaporte=567567).save()
Pacientes(nombre="Mau", tipo="Gato", edad="2", observaciones="Se le aplico desparacitante").save()
Pacientes(nombre="Pepito", tipo="Perro", edad="5", observaciones="Pata lastimada").save()
Pacientes(nombre="Negro", tipo="Perro", edad="12", observaciones="Diarrea con vomitos").save()
Pacientes(nombre="Jerry", tipo="Hamster", edad="3", observaciones="Tiene 3 años y sigue vivo").save()
Pacientes(nombre="Manchitas", tipo="Gato", edad="15", observaciones="Control anual").save()
Operarios(nombre="Carlos Montiel", legajo="12345", categoria="Oficial", observaciones="Es vago").save()
Operarios(nombre="Jorge Campos", legajo="54321", categoria="Ayudante", observaciones="Es muy bueno soldando").save()
Operarios(nombre="Lucas San Cristobal", legajo="89423", categoria="Medio Oficial", observaciones="El mejor 10").save()
Operarios(nombre="Marcelo Gallardo", legajo="54332", categoria="Ayudante", observaciones="En reposo por enfermedad").save()
Operarios(nombre="Cristobal Colon", legajo="12455", categoria="Ayudante", observaciones="Descubrio America").save()
print("Se cargo con éxito los usuarios de pruebas")