# Generated by Django 4.1.4 on 2023-01-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_final', '0004_mensaje_alter_post_publicado_el'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creador',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
