# Generated by Django 4.1.4 on 2022-12-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_pacientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='raza',
            new_name='tipo',
        ),
    ]
