# Generated by Django 4.1.4 on 2022-12-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_rename_raza_pacientes_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('legajo', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=1000)),
            ],
        ),
    ]
