# Generated by Django 4.1.3 on 2023-01-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0004_operarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operarios',
        ),
        migrations.DeleteModel(
            name='Pacientes',
        ),
    ]
